import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body
        className={`${inter.className} flex h-screen items-center justify-center bg-emerald-100`}
      >
        <main className=" m-auto h-full max-h-96  max-w-screen-lg flex-1 px-4">
          <div>
            <section className="h-full w-full rounded-3xl bg-white p-8 shadow-lg">
              {children}
            </section>
          </div>
        </main>
      </body>
    </html>
  );
}
